esphome:
  name: gate-sr-20-test
  friendly_name: gate-sr-20-test

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: !secret esphome_encryption_key

ota:
  - platform: esphome
    password: !secret esphome_ota_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

#  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Gate-Sr-20-Test Fallback Hotspot"
    password: "7Ndd1PtTkkmc"

#captive_portal:
uart:
  baud_rate: 9600
  tx_pin: GPIO43
  rx_pin: GPIO44
  id: uart_0
  
# Example configuration entry
sensor:
#  - platform: ultrasonic
#    trigger_pin: GPIO13
#    echo_pin: GPIO14
#    name: "Ultrasonic"
#    update_interval: 1s

  #https://esphome.io/components/sensor/jsn_sr04t.html
  - platform: "jsn_sr04t"
    name: "Distance"
    update_interval: 5s
    uart_id: uart_0
