esphome:
  name: aj_sr04m_uart
  friendly_name: AJ-SR04M UART

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Настройка UART
uart:
  id: uart_aj
  tx_pin: GPIO12
  rx_pin: GPIO13
  baud_rate: 9600

sensor:
  - platform: ultrasonic
    id: aj_sr04m
    name: "Уровень AJ-SR04M"
    uart_id: uart_aj
    update_interval: 1s
    timeout: 3m
    unit_of_measurement: "m"
    accuracy_decimals: 2
    filters:
      - median:
          window_size: 5
          send_every: 1
          send_first_at: 1
      - throttle: 1s
    on_value:
      then:
        - lambda: |-
            ESP_LOGD("sensor", "Расстояние: %.2f м", x);

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "AjSr04m Fallback"
    password: "fallback123"

captive_portal:
