substitutions:
  name: septic-tank
  friendly_name: septic_tank
  device_description: "Septic Tank Level"

esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  variant: ESP32C3
  board: esp32-c3-devkitm-1
  framework:
    type: arduino

# ⬇️ Для подробных логов
logger:
  level: DEBUG

api:
  encryption:
    key: "+lWI3+2o22duv581AzG58JUVv2BLz/RwkaeO++GiU3o="

ota:
  - platform: esphome
    password: "ff0f994b0a300f8c00108d94b64f4457"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "Septic-Tank Fallback"
    password: "DFiB8RjlKBvp"

captive_portal:

web_server:
  port: 80

uart:
  tx_pin: GPIO2
  rx_pin: GPIO1
  baud_rate: 9600
  debug:
    direction: BOTH

sensor:
  - platform: jsn_sr04t
    name: "Raw Septic Distance"
    id: raw_ultrasonic
    update_interval: 1s
    #model: aj_sr04m
#    filters:
#      - clamp:
#          min_value: 0.25
#          max_value: 3.0
#          ignore_out_of_range: true
#      - median:
#          window_size: 7
#          send_every: 3
#      - sliding_window_moving_average:
#          window_size: 5
#          send_every: 1
#          send_first_at: 1
    filters:
      - clamp:
         min_value: 0.4
         max_value: 3.0
         ignore_out_of_range: true
      - sliding_window_moving_average:
         window_size: 5
         send_every: 3 # TODO slow down to 10sec
         send_first_at: 3
      # Удалён фильтр delta, он мешал обновлению дальше по цепочке
    unit_of_measurement: "m"

  - platform: template
    name: "Septic Tank Distance"
    id: septic_distance
    unit_of_measurement: "cm"
    update_interval: never  # управляем вручную
    lambda: |-
      if (isnan(id(raw_ultrasonic).state)) return NAN;
      float result = id(raw_ultrasonic).state * 100.0;
      ESP_LOGD("septic_distance", "Raw to CM: %.2f", result);
      return round(result);
    on_value:
      then:
        - component.update: septic_fill
        - component.update: septic_status

  - platform: template
    name: "Septic Tank Fill Level"
    id: septic_fill
    unit_of_measurement: "%"
    accuracy_decimals: 0
    update_interval: never
    lambda: |-
      float level = id(septic_distance).state;
      float empty = id(empty_level_num).state;
      float full = id(full_level_num).state;

      ESP_LOGD("septic_fill", "Distance=%.2f, Empty=%.2f, Full=%.2f", level, empty, full);

      if (isnan(level) || isnan(empty) || isnan(full)) return NAN;
      if (level > empty) return 0.0;
      if (level < full) return 100.0;

      return round((1.0 - (level - full) / (empty - full)) * 100.0);

text_sensor:
  - platform: template
    name: "Septic Tank Status"
    id: septic_status
    update_interval: never
    lambda: |-
      float level = id(septic_fill).state;
      ESP_LOGD("septic_status", "Level=%.1f", level);

      if (isnan(level)) return {"⚠️ Ошибка измерения"};
      if (level < 50.0) return {"✅ Низкий уровень"};
      if (level < 85.0) return {"⚠️ Средний уровень"};
      if (level < 98.0) return {"🚨 Высокий уровень"};
      return {"🛑 Критический уровень!"};

binary_sensor:
  - platform: template
    name: "Septic Full Alert"
    id: septic_alert
    device_class: problem
    lambda: 'return id(septic_fill).state >= 98.0;'

light:
  - platform: binary
    name: "Septic Indicator LED"
    output: septic_led
    id: septic_light
    on_turn_on:
      - delay: 500ms
      - light.turn_off: septic_light

output:
  - platform: gpio
    pin: GPIO8
    id: septic_led

button:
  - platform: template
    name: "📏 Установить УРОВЕНЬ ПУСТО"
    on_press:
      then:
        - lambda: |-
            float val = id(raw_ultrasonic).state * 100.0;
            ESP_LOGI("calibration", "Уровень ПУСТО установлен на %.1f см", val);
            id(empty_level_num).publish_state(val);

  - platform: template
    name: "📏 Установить УРОВЕНЬ ПОЛНО"
    on_press:
      then:
        - lambda: |-
            float val = id(raw_ultrasonic).state * 100.0;
            ESP_LOGI("calibration", "Уровень ПОЛНО установлен на %.1f см", val);
            id(full_level_num).publish_state(val);

number:
  - platform: template
    name: "📀 Калибровка ПОЛНО"
    id: full_level_num
    optimistic: true
    restore_value: true
    min_value: 25
    max_value: 50
    step: 1
    initial_value: 30

  - platform: template
    name: "📀 Калибровка ПУСТО"
    id: empty_level_num
    optimistic: true
    restore_value: true
    min_value: 100
    max_value: 300
    step: 1
    initial_value: 200

# 🔄 Регулярное обновление цепочки
interval:
  - interval: 3s
    then:
      - component.update: septic_distance
