substitutions:
  name: ttn-inverter
  inv_id: ttn-inverter
  device_description: "Hybrid inverter via MAX communication"

  
esphome:
  name: ${name}
  comment: ${device_description}
  min_version: 2024.6.0
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB

esp32:
  variant: ESP32C3
  board: seeed_xiao_esp32c3
  framework:
    type: arduino
#    type: esp-idf

external_components:
  - source:
      type: local
      path: ./custom_components
#    components: [ solar_ttn ]
# Enable logging
logger:
#  level: WARN
  level: DEBUG
#  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "hgwo/GG/lG7OZ+7E01mlPSLmnDF2h0Ir+DBdAWOFWp4="

ota:
  - platform: esphome
    password: "9666b3dc9f968de6cf6f0bf63e6df765"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ttn-Inverter Fallback Hotspot"
    password: "oowz1NK2QMBW"

captive_portal:
web_server:

#uart:
#  id: uart_bus
#  tx_pin: GPIO21
#  rx_pin: GPIO20
#  baud_rate: 2400
#  stop_bits: 1
#  debug:
#    direction: BOTH
uart:
  id: uart_bus
  tx_pin: GPIO21
  rx_pin: GPIO20
  baud_rate: 2400
#  debug:
#    direction: BOTH
#    dummy_receiver: false
#    sequence:
#      - lambda: UARTDebug::log_string(direction, bytes);

solar_inverter:
  id: solar_inv
  uart_id: uart_bus
#  protocol_id:
#    name: "Protocol ID"
#  serial_number:
#    name: "Serial Number"

  #QMOD
#  device_mode_sensor:
#    name: "Device Mode inquiry RAW"
  device_mode_text:
    name: "Device Mode inquiry"

  # QFLAG switches
  buzzer_control:
    name: "Alarm Control"
  overload_bypass:
    name: "Overload Bypass"
  display_escape_to_default_page:
    name: "LCD Display Escape to Default Page"
  overload_restart:
    name: "Overload Restart"
  over_temperature_restart:
    name: "Over Temperature Restart"
  backlight_control:
    name: "Backlight Control"
  alarm_primary_source_interrupt:
    name: "Beeps on Primary Source Interrupt"
  fault_code_record:
    name: "Record Fault code"
  power_saving:
    name: "Power Saving Mode"
  data_log_popup:
    name: "Data Log Pop-up"
  grid_charge_enable:
    name: "Grid Charge Enable"  # не нашел описание
  solar_feed_to_grid:
    name: "Solar Feed to Grid"   # не нашел описание

## QPIWS Sensor
  warning_status_text:
    name: "Inverter Warnings"

## QBEQI
  equalization_enable:
    name: "Battery equalization"
  equalization_voltage:
    name: "Battery equalization voltage"
  equalization_time:
    name: "Battery equalization time"
  equalization_period:
    name: "Equalization interval"
  equalization_over_time:
    name: "Equalization timeout"
  equalization_active:
    name: "Equalization activated immediately"


## QPIGS Sensors
  grid_voltage:
    name: "Grid Voltage"
  grid_freq:
    name: "Grid Frequency"
  ac_output_voltage:
    name: "AC Output Voltage"
  ac_output_freq:
    name: "AC Output Frequency"
  output_apparent_power:
    name: "Apparent Power"
  output_active_power:
    name: "Active Power"
  output_load_percent:
    name: "Load %"
#  bus_voltage:
#    name: "Solar Inverter Bus Voltage"
  battery_voltage:
    name: "Battery Voltage"
  battery_charging_current:
    name: "Battery Charging Current"
  battery_capacity:
    name: "Battery Capacity"
#  inverter_temp:
#    name: "Inverter Heatsink Temperature"
  pv_input_current:
    name: "PV Input Current"
  pv_input_voltage:
    name: "PV Input Voltage"
#  battery_voltage_from_scc:
#    name: "Battery Voltage SCC"
  battery_discharge_current:
    name: "Battery Discharge Current"
#  pv_or_ac_powering_load:
#    name: "PV or AC feed the load"
#  config_changed:
#    name: "Configuration status"
#  scc_fw_updated:
#    name: " SCC  firmware  version"
#  load_on:
#    name: "Load status"
  charging_mode_text:
    name: "Charging Mode"
#  fan_on_voltage_offset:
#    name: "Battery  voltage  offset for fans on "
#  eeprom_version_text:
#    name: "EEPROM version"
  pv_charging_power:
    name: "PV Charging power"
#  charging_to_float
#    name: "flag for charging to floating mode"
#  inverter_on
#    name: "Switch On"
#  dustproof_installed
#    name: "flag  for  dustproof  installed"
  energy_solar_today:
    name: "Solar Energy Today"
  energy_solar_month:
    name: "Solar Energy This Month"
  energy_solar_year:
    name: "Solar Energy This Year"
  energy_solar_total:
    name: "Solar Energy This Total"
  energy_inverter_today:
    name: "Inverter Energy Today"
  energy_inverter_month:
    name: "Inverter Energy This Month"
  energy_inverter_year:
    name: "Inverter Energy This Year"
  energy_inverter_total:
    name: "Inverter Energy This Total"

## QPIRI Sensors
##  grid_rating_voltage:
##    name: "Grid Rating Voltage"
##  grid_rating_current:
##    name: "Grid Rating Current"
  ac_output_rating_voltage:
    name: "AC Output Rating Voltage"
  ac_output_rating_frequency:
    name: "AC Output Rating Frequency"
##  ac_output_rating_current:
##    name: "AC Output Rating Current"
##  ac_output_rating_apparent_power:
##    name: "AC Output Apparent Power"
##  ac_output_rating_active_power:
##    name: "AC Output Active Power"

##  battery_rating_voltage:
##    name: "Battery Rating Voltage"
  battery_recharge_voltage:
    name: "Back to utility source"
##  battery_undervoltage:
##    name: "Battery Under Voltage"
##  battery_bulk_voltage:
##    name: "Battery Bulk Voltage"
##  battery_float_voltage:
##    name: "Battery Float Voltage"
#  battery_type:
#    name: "Battery Type"
  max_ac_charging_current:
    name: "Max AC Charging Current"
  max_charging_current:
    name: "Max Total Charging Current"
##  input_voltage_range:
##    name: "Input Voltage Range"
#  output_source_priority:
#    name: "Output Source Priority"

#  charger_source_priority:
#    name: "Charger Source Priority"
##  parallel_max_number:
##    name: "Max Parallel Units"
##  machine_type:
##    name: "Machine Type"
##  topology:
##    name: "Topology" 
##  output_mode:
##    name: "Output Mode"
  battery_redischarge_voltage:
    name: "Back to battery"

##  pv_ok_condition:
##    name: "PV OK Condition for Parallel"
##  pv_power_balance:
##    name: "PV Power Balance"
##  max_charging_time_cv_stage:
##    name: "Max Charging Time CV Stage"
##  operation_logic:
##    name: "Operation Logic"
##  max_discharging_current:
##    name: "Max Discharging Current"
  